"""
image_describer_todo.py
Trying to udnerstand how to generate image descriptions locally to augment dataset automatically.

THIS FUNCTION HAS NEVER BEEN USED AND IT IS IS DEPRECADED.

Pipeline and requirements:
- PIL (Pillow) for image I/O (pillow==10.2.0 in simlingo environment).
- Optional: BLIP captioning via Hugging Face `transformers` (transformers==4.46.3) and `torch` (torch==2.2.0) for local image-to-text.
- Optional fast detection fallback: `ultralytics` (YOLO) if installed.
- This script will attempt BLIP first, then YOLO, then a template fallback.

Environment versions (from simlingo/environment.yaml):
- torch==2.2.0
- torchvision==0.17.0
- transformers==4.46.3
- pillow==10.2.0
- ultralytics (optional; not pinned in env file)

Output format and placement:
- For each image (for example: rgb/0010.jpg) the script writes a gzipped sidecar into a *_commentary folder
  placed next to the image tree. Example:
    rgb/0010.jpg  -->  rgb_commentary/0010.json.gz

Output JSON keys (to match simlingo commentary structure):
- image: path to rgb/0010.jpg
- commentary: (string) empty by default
- commentary_template: (string) empty by default
- cause_object_visible_in_image: (bool) default false
- cause_object: (dict) default {}
- cause_object_string: (string) default ''
- scenario_name: (string) default ''
- placeholder: (dict) default {}

Plus automatic fields generated by this tool:
- auto_caption: generated caption (BLIP or fallback template)
- detected_objects: list of detected object names (if any)
- caption_variants: small paraphrase variants
- provenance: dict with caption_model, detection_model, generated_at, source='local_describer'

Note: this script is intentionally conservative and self-contained; it does not call external APIs.
"""

from pathlib import Path
import json
import sys
import time
import argparse
import logging
import gzip
from typing import Iterable

try:
    from PIL import Image
except Exception:
    Image = None

try:
    from transformers import pipeline
    HAS_BLIP = True
except Exception:
    HAS_BLIP = False

try:
    from ultralytics import YOLO
    HAS_YOLO = True
except Exception:
    HAS_YOLO = False


def _caption_with_blip(image_path: Path):
    captioner = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")
    out = captioner(str(image_path), max_new_tokens=60)
    text = out[0]["generated_text"] if isinstance(out, list) else str(out)
    return text, "Salesforce/blip-image-captioning-base"


def _detect_with_yolo(image_path: Path):
    model = YOLO('yolov8n.pt')
    res = model(str(image_path))[0]
    names = []
    for box in getattr(res, 'boxes', []):
        try:
            cls = int(box.cls.cpu().numpy())
            names.append(res.names[cls])
        except Exception:
            continue
    return sorted(set(names)), 'yolov8n'


def _template_caption(detected_objects):
    if not detected_objects:
        return "An outdoor scene with no prominent objects detected."
    if len(detected_objects) == 1:
        return f"A {detected_objects[0]} in the scene."
    return f"A scene containing {' and '.join(detected_objects)}."


def _paraphrase_variants(base_caption, n=2):
    variants = [base_caption]
    if ',' in base_caption:
        variants.append(base_caption.replace(',', ' -'))
    if ' in the scene' in base_caption:
        variants.append(base_caption.replace(' in the scene', ' present in the image'))
    unique = []
    for v in variants:
        if v not in unique:
            unique.append(v)
        if len(unique) >= n+1:
            break
    return unique[1:]


def describe_image(path_str: str):
    p = Path(path_str)
    if not p.exists():
        raise FileNotFoundError(p)

    if Image is None:
        raise RuntimeError('PIL (Pillow) is required')

    t0 = time.time()

    caption = None
    caption_model = None
    detected = []
    detect_model = None

    if HAS_BLIP:
        try:
            caption, caption_model = _caption_with_blip(p)
        except Exception:
            caption = None

    if caption is None and HAS_YOLO:
        try:
            detected, detect_model = _detect_with_yolo(p)
            caption = _template_caption(detected)
        except Exception:
            caption = None

    if caption is None:
        caption = 'No caption available (missing models).'

    if not detected and HAS_YOLO:
        try:
            detected, detect_model = _detect_with_yolo(p)
        except Exception:
            detected = []

    variants = _paraphrase_variants(caption, n=2)

    provenance = {
        'caption_model': caption_model,
        'detection_model': detect_model,
        'generated_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'source': 'local_describer',
    }

    meta = {
        'auto_caption': caption,
        'detected_objects': detected,
        'caption_variants': variants,
        'provenance': provenance,
    }

    # Compatibility fields
    meta['image'] = str(p)
    meta.setdefault('commentary', '')
    meta.setdefault('commentary_template', '')
    meta.setdefault('cause_object_visible_in_image', False)
    meta.setdefault('cause_object', {})
    meta.setdefault('cause_object_string', '')
    meta.setdefault('scenario_name', '')
    meta.setdefault('placeholder', {})

    elapsed = time.time() - t0
    return meta, elapsed


def _iter_images_in_dir(dirpath: Path, exts: Iterable[str], recursive: bool):
    if recursive:
        for p in dirpath.rglob('*'):
            if p.is_file() and p.suffix.lower().lstrip('.') in exts:
                yield p
    else:
        for p in dirpath.iterdir():
            if p.is_file() and p.suffix.lower().lstrip('.') in exts:
                yield p


def _write_gz_commentary_json(image_path: Path, meta: dict, commentary_suffix: str = '_commentary'):
    # place commentary folder next to the image folder. e.g., rgb -> rgb_commentary
    img_dir = image_path.parent
    commentary_dir = Path(str(img_dir) + commentary_suffix)
    commentary_dir.mkdir(parents=True, exist_ok=True)

    # name the JSON the same basename as image: 0010.json.gz
    out_name = image_path.stem + '.json.gz'
    out_path = commentary_dir / out_name
    with gzip.open(out_path, 'wt', encoding='utf-8') as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
    return out_path


def _write_augmented_pair(image_path: Path, meta: dict, augmented_suffix: str = 'augmented', jpeg_quality: int = 85):
    """Create a sibling '<folder>_augmented/<stem>/' and place a .jpg copy
    of the image and a gzipped JSON commentary file inside that folder.

    Example: rgb/0000.png -> rgb_augmented/0000/0000.jpg and 0000.json.gz
    """
    img_dir = image_path.parent
    augmented_dir = Path(str(img_dir) + '_' + augmented_suffix)
    frame_dir = augmented_dir / image_path.stem
    frame_dir.mkdir(parents=True, exist_ok=True)

    # Save image as JPEG in the frame folder (convert if necessary)
    out_img_name = image_path.stem + '.jpg'
    out_img_path = frame_dir / out_img_name
    try:
        if Image is None:
            raise RuntimeError('PIL not available to convert image')
        img = Image.open(image_path)
        rgb_img = img.convert('RGB')
        rgb_img.save(out_img_path, format='JPEG', quality=jpeg_quality)
    except Exception:
        # Fallback: copy the file bytes (best-effort)
        from shutil import copy2
        try:
            copy2(image_path, out_img_path)
        except Exception:
            # Last resort: create an empty placeholder
            out_img_path.write_bytes(b'')

    # Write gzipped commentary JSON into the same folder
    out_json_path = frame_dir / (image_path.stem + '.json.gz')
    with gzip.open(out_json_path, 'wt', encoding='utf-8') as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)
    return out_img_path, out_json_path


def process_path(path_str: str, recursive: bool = False, exts=('jpg', 'jpeg', 'png'),
                 create_augmented: bool = True, augmented_suffix: str = 'augmented',
                 jpeg_quality: int = 85, skip_commentary: bool = False):
    p = Path(path_str)
    results = []
    if p.is_dir():
        files = list(_iter_images_in_dir(p, exts, recursive))
        logging.info('Found %d image(s) in %s', len(files), p)
        for img in sorted(files):
            try:
                meta, elapsed = describe_image(str(img))
                out_comment = None
                out_aug = (None, None)
                if not skip_commentary:
                    out_comment = _write_gz_commentary_json(img, meta)
                    logging.info('Wrote commentary %s (%.2fs)', out_comment, elapsed)
                if create_augmented:
                    out_aug = _write_augmented_pair(img, meta, augmented_suffix=augmented_suffix, jpeg_quality=jpeg_quality)
                    logging.info('Wrote augmented pair %s and %s', out_aug[0], out_aug[1])
                results.append((img, out_comment, out_aug, None))
            except Exception as e:
                logging.exception('Failed to describe %s: %s', img, e)
                results.append((img, None, (None, None), str(e)))
    else:
        try:
            meta, elapsed = describe_image(str(p))
            out_comment = None
            out_aug = (None, None)
            if not skip_commentary:
                out_comment = _write_gz_commentary_json(p, meta)
                logging.info('Wrote commentary %s (%.2fs)', out_comment, elapsed)
            if create_augmented:
                out_aug = _write_augmented_pair(p, meta, augmented_suffix=augmented_suffix, jpeg_quality=jpeg_quality)
                logging.info('Wrote augmented pair %s and %s', out_aug[0], out_aug[1])
            results.append((p, out_comment, out_aug, None))
        except Exception as e:
            logging.exception('Failed to describe %s: %s', p, e)
            results.append((p, None, (None, None), str(e)))
    return results


def main(argv):
    parser = argparse.ArgumentParser(description='Describe images and write gzipped commentary JSONs into *_commentary folders')
    parser.add_argument('path', help='Image file or directory')
    parser.add_argument('--recursive', '-r', action='store_true', help='If path is directory, search recursively')
    parser.add_argument('--ext', '-e', default='jpg,jpeg,png', help='Comma-separated accepted extensions (default: jpg,jpeg,png)')
    parser.add_argument('--no-augmented', action='store_true', help='Do not create rgb_augmented-style folders (only write commentary sidecars)')
    parser.add_argument('--aug-suffix', default='augmented', help='Suffix name for augmented sibling folders (default: "augmented")')
    parser.add_argument('--jpeg-quality', type=int, default=85, help='JPEG quality for saved augmented images (default: 85)')
    parser.add_argument('--skip-commentary', action='store_true', help='Skip writing the _commentary sidecar files (only create augmented pairs)')
    parser.add_argument('--no-models', action='store_true', help='Disable BLIP/YOLO model usage (prevent downloads)')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose logging')
    args = parser.parse_args(argv[1:])

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO, format='[%(levelname)s] %(message)s')

    if args.no_models:
        # disable attempts to load heavy models (safe mode)
        global HAS_BLIP, HAS_YOLO
        HAS_BLIP = False
        HAS_YOLO = False

    results = process_path(
        args.path,
        recursive=args.recursive,
        exts=[x.strip().lower() for x in args.ext.split(',') if x.strip()],
        create_augmented=not args.no_augmented,
        augmented_suffix=args.aug_suffix,
        jpeg_quality=args.jpeg_quality,
        skip_commentary=args.skip_commentary,
    )

    succeeded = sum(1 for _, o, a, err in results if (o or (a and a[0])) and not err)
    failed = sum(1 for _, o, a, err in results if err)
    logging.info('Summary: %d succeeded, %d failed', succeeded, failed)
    return 0 if failed == 0 else 1


if __name__ == '__main__':
    sys.exit(main(sys.argv))
